### ISSUE TITLE
Unexpected error: `AttributeError: 'NoneType' object has no attribute 'storage'` on `prefix = batch_config.storage.prefix or ""`

### ISSUE THREAD

**Issue by florian-ernst-alan** [MeltanoLabs/target-snowflake#26]
When running a simple ELT from Slack to Snowflake, I get the following error:

```
2023-06-01T14:52:08.118395Z [info     ] 2023-06-01 16:52:08,118 | INFO     | target-snowflake     | Target 'target-snowflake' completed reading 4299 lines of input (4297 records, (0 batch manifests, 1 state messages). cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.125457Z [info     ] Traceback (most recent call last): cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.125600Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/bin/target-snowflake", line 8, in <module> cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.125722Z [info     ]     sys.exit(TargetSnowflake.cli()) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.125799Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__ cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.125861Z [info     ]     return self.main(*args, **kwargs) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.125917Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.126391Z [info     ]     rv = self.invoke(ctx)      cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.126451Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.126953Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.127037Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.127106Z [info     ]     return __callback(*args, **kwargs) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.127707Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 572, in cli cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.127818Z [info     ]     target.listen(file_input)  cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.128521Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 35, in listen cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.128606Z [info     ]     self._process_endofpipe()  cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.128678Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 287, in _process_endofpipe cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.129194Z [info     ]     self.drain_all(is_endofpipe=True) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.129266Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 449, in drain_all cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.129802Z [info     ]     self._drain_all(list(self._sinks_active.values()), self.max_parallelism) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.129863Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 482, in _drain_all cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.129918Z [info     ]     Parallel()(delayed(_drain_sink)(sink=sink) for sink in sink_list) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.130603Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__ cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.130743Z [info     ]     self.retrieve()            cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.131340Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.131401Z [info     ]     self._output.extend(job.get(timeout=self.timeout)) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.131464Z [info     ]   File "/Users/florian.ernst/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/pool.py", line 771, in get cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.132069Z [info     ]     raise self._value          cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.132124Z [info     ]   File "/Users/florian.ernst/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/pool.py", line 125, in worker cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.132721Z [info     ]     result = (True, func(*args, **kwds)) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.132775Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 620, in __call__ cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.132832Z [info     ]     return self.func(*args, **kwargs) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.133331Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/joblib/parallel.py", line 288, in __call__ cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.133386Z [info     ]     return [func(*args, **kwargs) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.133998Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/joblib/parallel.py", line 288, in <listcomp> cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.134056Z [info     ]     return [func(*args, **kwargs) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.134111Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 479, in _drain_sink cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.134608Z [info     ]     self.drain_one(sink)       cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.134668Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 469, in drain_one cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.135177Z [info     ]     sink.process_batch(draining_status) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.135233Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/singer_sdk/sinks/sql.py", line 253, in process_batch cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.135282Z [info     ]     self.bulk_insert_records(  cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.135847Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/sinks.py", line 348, in bulk_insert_records cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.135899Z [info     ]     encoding, files = self.get_batches( cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.136618Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/target_snowflake/sinks.py", line 374, in get_batches cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.136709Z [info     ]     prefix = batch_config.storage.prefix or "" cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.136777Z [info     ] AttributeError: 'NoneType' object has no attribute 'storage' cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr

2023-06-01T14:52:08.165845Z [info     ] 2023-06-01 16:52:08,165 | INFO     | snowflake.connector.cursor | query: [ROLLBACK] cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.170986Z [info     ] 2023-06-01 16:52:08,169 | ERROR    | sqlalchemy.pool.impl.QueuePool | Exception during reset or similar cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr

2023-06-01T14:52:08.171085Z [info     ] Traceback (most recent call last): cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.171149Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 763, in _finalize_fairy cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.171208Z [info     ]     fairy._reset(pool, transaction_was_reset) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.171282Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1038, in _reset cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.171334Z [info     ]     pool._dialect.do_rollback(self) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.171383Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.171878Z [info     ]     dbapi_connection.rollback() cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.171929Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 647, in rollback cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.172428Z [info     ]     self.cursor().execute("ROLLBACK") cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.172476Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 801, in execute cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.172969Z [info     ]     ret = self._execute_helper(query, **kwargs) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.173030Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 521, in _execute_helper cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.173079Z [info     ]     ret = self._connection.cmd_query( cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.173679Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1067, in cmd_query cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.173728Z [info     ]     ret = self.rest.request(   cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.174303Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 477, in request cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.174353Z [info     ]     return self._post_request( cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.174401Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 716, in _post_request cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.174889Z [info     ]     ret = self.fetch(          cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.174938Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 814, in fetch cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.175474Z [info     ]     ret = self._request_exec_wrapper( cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.175523Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 937, in _request_exec_wrapper cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.175578Z [info     ]     raise e                    cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.176179Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 857, in _request_exec_wrapper cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.176237Z [info     ]     return_object = self._request_exec( cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.176937Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 1131, in _request_exec cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.176991Z [info     ]     raise err                  cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.177041Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/network.py", line 1033, in _request_exec cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.177556Z [info     ]     raw_ret = session.request( cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.177604Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/vendored/requests/sessions.py", line 577, in request cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.178420Z [info     ]     settings = self.merge_environment_settings( cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.178498Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/vendored/requests/sessions.py", line 759, in merge_environment_settings cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.178994Z [info     ]     env_proxies = get_environ_proxies(url, no_proxy=no_proxy) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.179050Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/vendored/requests/utils.py", line 825, in get_environ_proxies cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.179794Z [info     ]     if should_bypass_proxies(url, no_proxy=no_proxy): cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.179853Z [info     ]   File "/Users/florian.ernst/Alan/meltano/alan_slack/.meltano/loaders/target-snowflake/venv/lib/python3.10/site-packages/snowflake/connector/vendored/requests/utils.py", line 809, in should_bypass_proxies cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.179906Z [info     ]     bypass = proxy_bypass(parsed.hostname) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.180531Z [info     ]   File "/Users/florian.ernst/.pyenv/versions/3.10.1/lib/python3.10/urllib/request.py", line 2649, in proxy_bypass cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.180596Z [info     ]     return proxy_bypass_macosx_sysconf(host) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.180647Z [info     ]   File "/Users/florian.ernst/.pyenv/versions/3.10.1/lib/python3.10/urllib/request.py", line 2626, in proxy_bypass_macosx_sysconf cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.181135Z [info     ]     return _proxy_bypass_macosx_sysconf(host, proxy_settings) cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.181203Z [info     ]   File "/Users/florian.ernst/.pyenv/versions/3.10.1/lib/python3.10/urllib/request.py", line 2568, in _proxy_bypass_macosx_sysconf cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.181721Z [info     ]     from fnmatch import fnmatch cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.181774Z [info     ] ImportError: sys.meta_path is None, Python is likely shutting down cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.181919Z [info     ] 2023-06-01 16:52:08,170 | INFO     | snowflake.connector.connection | closed cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.182252Z [info     ] 2023-06-01 16:52:08,171 | INFO     | snowflake.connector.connection | No async queries seem to be running, deleting session cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.224127Z [error    ] Loading failed                 code=1 message=2023-06-01 16:52:08,171 | INFO     | snowflake.connector.connection | No async queries seem to be running, deleting session name=meltano run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake
```

I added some blank lines to clearly show the 3 distinct parts of the logs. Here, I think the 2 interesting lines are:
```
2023-06-01T14:52:08.136709Z [info     ]     prefix = batch_config.storage.prefix or "" cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
2023-06-01T14:52:08.136777Z [info     ] AttributeError: 'NoneType' object has no attribute 'storage' cmd_type=loader name=target-snowflake run_id=f0b21644-eafb-41d7-8924-31c7ba04feb4 state_id=2023-06-01T145159--tap-slack--target-snowflake stdio=stderr
```

Not sure what's wrong here.

**Comment by pnadolny13** [comment]
@florian-ernst-alan I ran into this also and have a [PR](https://github.com/MeltanoLabs/target-snowflake/pull/25) to fix it. This target is still considered to be in development status. I'm spending some time on in now though so it should be in better shape soon.
