### ISSUE TITLE
If schema isn't specified weird stuff happens

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-snowflake#88]
While fixing https://github.com/MeltanoLabs/target-snowflake/issues/87 I ran into my schema not getting created automatically, really I think we should just make https://github.com/MeltanoLabs/target-snowflake/blob/main/target_snowflake/target.py#L46 required, and  probably check that the value isn't null somewhere. 

When rolling back my transactions it was trying to rollback from the DATABASE.None schema which didn't exist. I think just forcing a schema to exist would help this, but there could be other options here!

**Comment by visch** [comment]
Hit this again today 

```
2023-07-27T21:47:56.012960Z [info     ] snowflake.connector.errors.ProgrammingError: 002003 (02000): 01adea3b-0001-3b6d-0004-428e0002f182: SQL compilation error: cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.013154Z [info     ] Schema 'ZENOTI.NONE' does not exist or not authorized. cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.013340Z [info     ]                                cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.013557Z [info     ] The above exception was the direct cause of the following exception: cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.013748Z [info     ]                                cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.013965Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.014183Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/bin/target-snowflake", line 8, in <module> cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.014344Z [info     ]     sys.exit(TargetSnowflake.cli()) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.014521Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__ cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.014689Z [info     ]     return self.main(*args, **kwargs) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.014884Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.015071Z [info     ]     rv = self.invoke(ctx)      cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.015257Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.015444Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.015692Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.015878Z [info     ]     return __callback(*args, **kwargs) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.016063Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 550, in invoke cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.016249Z [info     ]     target.listen(file_input)  cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.016478Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 34, in listen cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.016670Z [info     ]     self._process_lines(file_input) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.016857Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 291, in _process_lines cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.017045Z [info     ]     counter = super()._process_lines(file_input) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.017234Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 93, in _process_lines cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.017421Z [info     ]     self._process_record_message(line_dict) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.017677Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 354, in _process_record_message cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.017873Z [info     ]     self.drain_one(sink)       cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.018059Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 495, in drain_one cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.018246Z [info     ]     sink.process_batch(draining_status) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.018432Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/sinks/sql.py", line 267, in process_batch cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.018620Z [info     ]     self.bulk_insert_records(  cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.018808Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/sinks.py", line 142, in bulk_insert_records cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.018994Z [info     ]     self.insert_batch_files_via_internal_stage( cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.019181Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/sinks.py", line 205, in insert_batch_files_via_internal_stage cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.019370Z [info     ]     self.connector.drop_file_format(file_format=file_format) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.019564Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/connector.py", line 485, in drop_file_format cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.019790Z [info     ]     conn.execute(drop_statement, **kwargs) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.020005Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.020193Z [info     ]     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.020381Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.020568Z [info     ]     return connection._execute_clauseelement( cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.020776Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.021041Z [info     ]     ret = self._execute_context( cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.021283Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.021474Z [info     ]     self._handle_dbapi_exception( cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.021698Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.021885Z [info     ]     util.raise_(               cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.022076Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_ cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.022262Z [info     ]     raise exception            cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.022449Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.022810Z [info     ]     self.dialect.do_execute(   cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.023110Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.023305Z [info     ]     cursor.execute(statement, parameters) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.023496Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 910, in execute cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.023703Z [info     ]     Error.errorhandler_wrapper(self.connection, self, error_class, errvalue) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.023983Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.024190Z [info     ]     handed_over = Error.hand_to_other_handler( cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.024382Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.024615Z [info     ]     cursor.errorhandler(connection, cursor, error_class, error_value) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.024805Z [info     ]   File "/home/visch/git/zenoti_2_snowflake_sample/tap-zenoti/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.024994Z [info     ]     raise error_class(         cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.025182Z [info     ] sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002003 (02000): 01adea3b-0001-3b6d-0004-428e0002f182: SQL compilation error: cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.025374Z [info     ] Schema 'ZENOTI.NONE' does not exist or not authorized. cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.025563Z [info     ] [SQL: drop file format if exists ZENOTI.None."BI_FACTINVOICEITEM-b1a709a0-f0ae-4df6-ab87-997e655d7dfe"] cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.025992Z [info     ] (Background on this error at: https://sqlalche.me/e/14/f405) cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.077047Z [info     ] 2023-07-27 17:47:56,076 | INFO     | snowflake.connector.connection | closed cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.077374Z [info     ] 2023-07-27 17:47:56,076 | INFO     | snowflake.connector.connection | No async queries seem to be running, deleting session cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.230525Z [info     ] 2023-07-27 17:47:56,230 | INFO     | snowflake.connector.connection | closed cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.230826Z [info     ] 2023-07-27 17:47:56,230 | INFO     | snowflake.connector.connection | No async queries seem to be running, deleting session cmd_type=elb consumer=True name=target-snowflake producer=False stdio=stderr string_id=target-snowflake
2023-07-27T21:47:56.400732Z [error    ]
```
